name: lcov
version: 0.3.1

author: CÃ©dric Belin <cedric@belin.io>
description: Parse and format LCOV coverage reports.
documentation: https://cedx.github.io/lcov.dart
homepage: https://github.com/cedx/lcov.dart

environment:
  sdk: '>=1.21.0 <2.0.0'

dev_dependencies:
  coverage: ^0.9.2
  grinder: ^0.8.0
  test: ^0.12.19
